import { z } from 'zod';
import { dataMode, request } from './client';

const finite = z.number().finite();

export const inventoryActions = [
  'RESTOCK',
  'HOLD_SPEND',
  'EXPEDITE',
  'CLEAR_EXCESS',
  'SCALE_DEMAND',
  'WATCH',
  'CONTINUE',
] as const;
export type InventoryAction = (typeof inventoryActions)[number];

export const inventorySkuSchema = z.object({
  sku: z.string().min(1),
  title: z.string(),
  category: z.string().nullable(),
  promoted: z.boolean(),
  on_hand: z.number().int(),
  reserved: z.number().int(),
  available: z.number().int(),
  inbound_qty: z.number().int().nonnegative(),
  expected_arrival: z.string().nullable(),
  units_7d_avg: finite.nonnegative(),
  units_28d_avg: finite.nonnegative(),
  velocity_change: finite.nullable(),
  cover_days: finite.nullable(),
  reorder_point: finite,
  safety_stock: finite,
  stockout_days_28d: z.number().int().nonnegative(),
  net_revenue_28d: finite,
  cba_28d: finite,
  ad_spend_28d: finite.nonnegative(),
  action: z.enum(inventoryActions),
  reason: z.string().min(1),
});
export type InventorySku = z.infer<typeof inventorySkuSchema>;

export const inventorySchema = z.object({
  as_of: z.string(),
  window_days: z.number().int().positive(),
  lead_time_days: z.number().int().nonnegative(),
  excess_cover_days: finite.positive(),
  velocity_alert: finite.positive(),
  skus: z.array(inventorySkuSchema),
  note: z.string(),
});
export type Inventory = z.infer<typeof inventorySchema>;

// Illustrative frontend rows: they exercise every recommendation, not the engine's rules or world output.
function row(
  sku: string,
  title: string,
  category: string,
  available: number,
  inbound: [number, string | null],
  v7: number,
  v28: number,
  spend: number,
  revenue: number,
  action: InventoryAction,
  reason: string,
  stockoutDays = 0,
): InventorySku {
  return {
    sku,
    title,
    category,
    promoted: true,
    on_hand: available,
    reserved: 0,
    available,
    inbound_qty: inbound[0],
    expected_arrival: inbound[1],
    units_7d_avg: v7,
    units_28d_avg: v28,
    velocity_change: v28 ? Math.round((v7 / v28 - 1) * 10000) / 10000 : null,
    cover_days: v28 ? Math.round((available / v28) * 10) / 10 : null,
    reorder_point: Math.round(v28 * 14 * 1.15),
    safety_stock: Math.round(v28 * 14 * 0.15),
    stockout_days_28d: stockoutDays,
    net_revenue_28d: revenue,
    cba_28d: Math.round(revenue * 0.38),
    ad_spend_28d: spend,
    action,
    reason,
  };
}

const fixture: Inventory = {
  as_of: '2026-09-30',
  window_days: 28,
  lead_time_days: 14,
  excess_cover_days: 45,
  velocity_alert: 0.25,
  note: 'Illustrative frontend inventory. Connect the API to read ERP stock, store demand and attributed ad spend.',
  skus: [
    row(
      'HERO-001',
      'Hero serum 50 ml',
      'Skincare',
      0,
      [640, '2026-10-01'],
      31.2,
      25.4,
      190800,
      512000,
      'HOLD_SPEND',
      'Out of stock; 640 inbound units arrive in 1 day. Its ads keep spending: reduce them until stock lands. Selling 23% faster than its 28-day average.',
      3,
    ),
    row(
      'REFILL-006',
      'Serum refill pouch',
      'Skincare',
      224,
      [0, null],
      93.4,
      74.5,
      233700,
      1104000,
      'RESTOCK',
      'Available plus confirmed inbound (224 units) is at or below the reorder point (1,199); reorder now to cover the 14-day lead time. Selling 25% faster than its 28-day average.',
    ),
    row(
      'SPF-012',
      'Daily SPF 50',
      'Sun care',
      89,
      [720, '2026-10-06'],
      29.4,
      24.3,
      218000,
      466000,
      'HOLD_SPEND',
      'Sells out in about 4 days; 720 inbound units arrive in about 6 days. Its ads keep spending: reduce them until stock lands.',
    ),
    row(
      'BUNDLE-004',
      'Starter bundle',
      'Bundles',
      2424,
      [0, null],
      83.3,
      66.5,
      110000,
      1380000,
      'SCALE_DEMAND',
      'Selling 25% faster than its 28-day average with 36 days of cover: stock supports more spend.',
    ),
    row(
      'MIST-021',
      'Hydrating face mist',
      'Skincare',
      893,
      [1980, '2026-10-11'],
      84.2,
      65.8,
      80600,
      702000,
      'WATCH',
      'Selling 28% faster than its 28-day average; 14 days of cover against a 14-day lead time. Check the next reorder.',
    ),
    row(
      'LIP-033',
      'Tinted lip balm',
      'Lip care',
      426,
      [823, '2026-10-12'],
      29.6,
      22.3,
      85000,
      248000,
      'WATCH',
      'Selling 33% faster than its 28-day average; 19 days of cover against a 14-day lead time. Check the next reorder.',
    ),
    row(
      'COAT-110',
      'Winter body butter',
      'Body care',
      3253,
      [0, null],
      38.3,
      28.8,
      41000,
      384000,
      'CLEAR_EXCESS',
      '113 days of cover, above the 45-day excess band; the Inventory Clearance objective can move spend toward it.',
    ),
    row(
      'SCRUB-118',
      'Coffee body scrub',
      'Body care',
      2615,
      [0, null],
      41.3,
      29.5,
      150000,
      401000,
      'CLEAR_EXCESS',
      '89 days of cover, above the 45-day excess band; the Inventory Clearance objective can move spend toward it.',
    ),
    row(
      'CLEANSE-002',
      'Gel cleanser',
      'Skincare',
      1113,
      [0, null],
      42.0,
      38.9,
      524900,
      1270000,
      'CONTINUE',
      '29 days of cover; demand within its normal range.',
    ),
    row(
      'TONER-007',
      'Balancing toner',
      'Skincare',
      940,
      [0, null],
      42.3,
      39.1,
      141800,
      698000,
      'CONTINUE',
      '24 days of cover; demand within its normal range.',
    ),
    row(
      'MASK-015',
      'Clay mask',
      'Skincare',
      78,
      [733, '2026-10-01'],
      28.9,
      25.8,
      85100,
      301000,
      'CONTINUE',
      '3 days of cover and 733 inbound units arrive in 1 day; demand within its normal range.',
    ),
    row(
      'EYE-040',
      'Eye cream',
      'Skincare',
      0,
      [607, '2026-10-04'],
      28.1,
      25.5,
      0,
      0,
      'EXPEDITE',
      'Out of stock; 607 inbound units arrive in about 4 days. Bring the inbound forward if possible.',
      4,
    ),
  ],
};

export const inventory = {
  get: () =>
    dataMode === 'api' ? request('/data/inventory', inventorySchema) : Promise.resolve(fixture),
};
